
name: Flutter CI/CD

on:
    push:
      branches:
        - '**'
jobs:
  mobile-app-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: cd mobile && dart format .
      - name: Commit and push changes
        run: git diff --exit-code || { git config user.name "GitHub Actions"; git config user.email "actions@github.com"; git add .; git commit -m "Apply dart formatting"; git push origin $GITHUB_REF; }
