
name: Flutter CI/CD

on:
    push:
      branches:
        - '**'
jobs:
  mobile-app-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart format .
      - name: Commit and push changes to new branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b format
          git commit -am "Apply dart formatting"
          git push origin format
      - name: Create Pull Request
        run: |
          gh pr create -B main -H format --title 'Merge format into main' --body 'Created by Github action'
